apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system # TODO: stackend
resources:
  - namespace.yaml
  - stackend-service.yaml
  - stackend-deployment.yaml
  - stackend-cm0-configmap.yaml
  - stackend-cm1-configmap.yaml
  - stackend-cm2-configmap.yaml
  - stackend--env-configmap.yaml
