apiVersion: v1
data:
  AIRTABLE_CLIENT_ID: ""
  AIRTABLE_CLIENT_SECRET: ""
  AIRTABLE_CODE_VERIFIER: ""
  ALLOW_PARALLEL_FLOW_EXECUTION: "true"
  ANTHROPIC_API_KEY: ""
  APIFY_API_KEY: ""
  APIFY_MAX_CRAWL_DEPTH: ""
  APIFY_TOKEN: ""
  APRYSE_API_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  AZURE_APP_ID: ""
  AZURE_APP_SECRET: ""
  AZURE_OPENAI_ENDPOINT: ""
  AZURE_OPENAI_KEY: ""
  AZURE_OPENAI_REGION: ""
  BEDROCK_ACCESS_KEY_ID: ""
  BEDROCK_PROFILE: ""
  BEDROCK_REGION: ""
  BEDROCK_SECRET_ACCESS_KEY: ""
  CALENDLY_CLIENT_ID: ""
  CALENDLY_CLIENT_SECRET: ""
  CELERY_BACKEND_URL: redis://redis-headless.redis.svc.cluster.local:6379
  CELERY_BROKER_URL: redis://redis-headless.redis.svc.cluster.local:6379
  CEREBRAS_API_KEY: ""
  CHAMALEON_API_KEY: ""
  COHERE_API_KEY: ""
  CONFLUENCE_CLIENT_ID: ""
  CONFLUENCE_CLIENT_SECRET: ""
  DEEPGRAM_API_KEY: ""
  DEPLOYMENT_ENVIRONMENT: production_stackend
  DROPBOX_APP_KEY: ""
  DROPBOX_APP_SECRET: ""
  EASYCRON_KEY: ""
  ELEVEN_LABS_API_KEY: ""
  ENVIRONMENT: development
  EXA_API_KEY: ""
  FIRECRAWL_KEY: ""
  GMAIL_CLIENT_ID: ""
  GMAIL_CLIENT_SECRET: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GOOGLE_PALM_API: ""
  GOOGLE_SHEET_PRIVATE_KEY: ""
  GOOGLE_SHEET_SPREADSHEET_ID: ""
  GOOGLE_SHEET_WORKSHEET_NAME: ""
  GOOGLE_WORKSPACE_CLIENT_ID: ""
  GOOGLE_WORKSPACE_CLIENT_SECRET: ""
  GROQ_AI_API_KEY: ""
  HUBSPOT_CLIENT_ID: ""
  HUBSPOT_CLIENT_SECRET: ""
  HUGGINGFACE_API_KEY: ""
  INDEXING_API_URL: http://supabase-supabase-kong.flux-system.svc.cluster.local:8000
  JIRA_CLIENT_ID: ""
  JIRA_CLIENT_SECRET: ""
  LOCAL_CALENDLY_CLIENT_ID: ""
  LOCAL_CALENDLY_CLIENT_SECRET: ""
  MAILCHIMP_API_KEY: ""
  MISTRAL_API_KEY: ""
  MONGODB_URI: mongodb://stack_user:LYqffkJBizek@mongodb:27017
  NGROK_AUTHTOKEN: ""
  NGROK_DOMAIN: ""
  NGROK_URL: ""
  NOTION_CLIENT_ID: ""
  NOTION_CLIENT_SECRET: ""
  OPENAI_API_KEY: ""
  OPENAI_API_KEY_1: ""
  OPENAI_API_KEY_2: ""
  OPENAI_API_KEY_3: ""
  OPENAI_API_KEY_4: ""
  OPENAI_API_KEY_5: ""
  OUTLOOK_CLIENT_ID: ""
  OUTLOOK_CLIENT_SECRET: ""
  PERPLEXITY_API_KEY: ""
  PINECONE_API_KEY: ""
  PINECONE_ENV: ""
  POLYTOMIC_API_KEY: ""
  POPLARML_KEY: ""
  POSTGRES_DB_HOST: supabase-supabase-db.flux-system.svc.cluster.local
  POSTGRES_DB_NAME: postgres
  POSTGRES_DB_PASSWORD: "your-super-secret-and-long-postgres-password"
  POSTGRES_DB_PORT: "5432"
  POSTGRES_DB_USER: postgres
  PSPDFKIT_API_KEY: ""
  REDIS_URL: redis://redis-headless.redis.svc.cluster.local:6379
  REDIS_US_EAST_URL: redis://redis-headless.redis.svc.cluster.local:6379
  REDUCTO_AUTH_TOKEN: ""
  REPL_URL: http://stackrepl:8000/execute_code #TODO
  REPLICATE_API_TOKEN: ""
  RESEND_API_KEY: ""
  S3_AWS_ACCESS_KEY: supa-storage
  S3_AWS_REGION: us-east-1
  S3_AWS_SECRET_ACCESS_KEY: 4PKqpr8bnIsVSHqnpSaMKPnCy0uC9N8O
  S3_ENDPOINT_URL: http://d:9000 # TODO
  S3_USERCONTENT_PUBLIC_BUCKET: stack-ai-usercontent
  SCRAPIN_API_KEY: ""
  SELF_HOSTED_WEAVIATE: "true"
  SERP_API_KEY: ""
  SERPER_API_KEY: ""
  SERVICENOW_CLIENT_ID: ""
  SERVICENOW_CLIENT_SECRET: ""
  STACKEND_API_URL: http://supabase-supabase-kong.flux-system.svc.cluster.local:8000
  STACKWEB_URL: http://stackweb.stackweb.svc.cluster.local:3000
  STRIPE_SECRET_KEY: '?'
  STRIPE_WEBHOOK_SECRET: ""
  SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiZXhwIjoyMDE1MTc2ODAwfQ.Wk-XZoMEJV6vdN3hbYMVz2n3XDmRbUcHxYJ33ej06bE
  SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3NDc5MjI5NTUsImV4cCI6MTkwNTYwMjk1NX0.sNVS9zwrVlkKGhrhMlZVrsCECsO4Ughb_e6FfNq6nlc
  SUPABASE_URL: http://supabase-supabase-kong.flux-system.svc.cluster.local:8000
  TOGETHER_AI_API_KEY: ""
  TWILIO_AUTH_TOKEN: ""
  TYPEFORM_CLIENT_ID: ""
  TYPEFORM_CLIENT_SECRET: ""
  UNSTRUCTURED_API_KEY: DrJTnB74EbyT
  UNSTRUCTURED_URL: http://unstructured:8000/general/v0/general # TODO
  VERTEX_AI_PROJECT_ID: ""
  VERTEX_AI_PROJECT_LOCATION: ""
  VERTEX_AI_SERVICE_ACCOUNT_MAIL: ""
  VERTEX_AI_SERVICE_ACCOUNT_PKEY: ""
  VERTEX_AI_SERVICE_ACCOUNT_PKEY_ID: ""
  WEAVIATE_KEY: oSyM0JgYluHi
  WEAVIATE_URL: weaviate.weaviate.svc.cluster.local # possibly should be weaviate-headless
  WOLFRAM_APP_ID: ""
  XAI_API_KEY: ""
  ZENDESK_CLIENT_ID: ""
  ZENDESK_CLIENT_SECRET: ""
  llama_parse_api_key: ""
  multi_on_api_key: ""
  sentry_dsn: ""
  sharepoint_client_id: ""
  sharepoint_client_secret: ""
  supabase_encryption_key: EvZZRZ9To4aRYraXdpvC19O/qLpiJ7m6MEr8Ly6BJM0=
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: celery-worker-stackend--env
  name: stackend--env
